{
 "title": "Test Service Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Response time summary (using Prometheus histogram)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Response Time Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.25, test_service_response_time_seconds_bucket{job=\"spring-app\"})",
     "legendFormat": "0.25"
    },
    {
     "expr": "histogram_quantile(0.5, test_service_response_time_seconds_bucket{job=\"spring-app\"})",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.75, test_service_response_time_seconds_bucket{job=\"spring-app\"})",
     "legendFormat": "0.75"
    }
   ]
  },
  {
   "title": "Current response time histogram at ${__to:date:YYYY-MM-DD HH:mm}",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reponses" } },
   "targets": [
    {
     "expr": "test_service_response_time_seconds_bucket{job=\"spring-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Test Service Response time seconds",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "test_service_response_time_seconds_bucket{job=\"spring-app\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Visits summary (using Prometheus histogram)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "Number of visit quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "histogram_quantile(0.25, test_service_response_time_seconds_bucket{job=\"spring-app\"})",
     "legendFormat": "0.25 quantile"
    },
    {
     "expr": "histogram_quantile(0.50, test_service_visits_bucket{job=\"spring-app\"})",
     "legendFormat": "0.50 quantile"
    },
    {
     "expr": "histogram_quantile(0.75, test_service_visits_bucket{job=\"spring-app\"})",
     "legendFormat": "0.75 quantile"
    },
    {
     "expr": "histogram_quantile(0.95, test_service_visits_bucket{job=\"spring-app\"})",
     "legendFormat": "0.95 quantile"
    }
   ]
  },
  {
   "title": "Current visit histogram at ${__to:date:YYYY-MM-DD HH:mm}",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "visits" } },
   "targets": [
    {
     "expr": "test_service_visits_bucket{job=\"spring-app\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Number of visits ",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "test_service_visits_bucket{job=\"spring-app\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Number of visits, approx quantile values from histogram",
   "type": "table",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "histogram_quantile(0.25, test_service_visits_bucket{job=\"spring-app\"})",
     "legendFormat": "0.25"
    },
    {
     "expr": "histogram_quantile(0.50, test_service_visits_bucket{job=\"spring-app\"})",
     "legendFormat": "0.50"
    },
    {
     "expr": "histogram_quantile(0.75, test_service_visits_bucket{job=\"spring-app\"})",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.95, test_service_visits_bucket{job=\"spring-app\"})",
     "legendFormat": "0.95"
    }
   ]
  },
  {
   "title": "Visit summary (using Prometheus summary metric)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 }
  },
  {
   "title": "Response Time Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "test_service_visits2{job=\"spring-app\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Number of visits, from summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 43 },
   "targets": [
    {
     "expr": "test_service_visits2{job=\"spring-app\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}